server:
  port: 8082

spring:
  security:
    user:
      name: user
      password: p123
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: corsi-service
              uri: http://localhost:8080
              predicates:
                - Path= /corsi/**

            - id: docenti-discenti-service
              uri: http://localhost:8081
              predicates:
                - Path= /docenti/**, /discenti/**

