server:
  port: 8082

spring:
  security:
    user:
      name: user
      password: p123
  cloud:
    gateway:
      routes:
        - id: corsi-service
          uri: http://localhost:8080
          predicates:
            - Path=/corsi/**
          filters:
            - StripPrefix=1

        - id: docenti-discenti-service
          uri: http://localhost:8081
          predicates:
            - Path=/docenti/**, /discenti/**
          filters:
            - StripPrefix=1

