server:
  port: 8082

spring:
  application:
    name: api-gateway
  datasource:
#    url: jdbc:postgresql://localhost:5432/Database_JWT_users
    url: jdbc:postgresql://localhost:5432/Database_Corso_2025_05
    username: postgres
    password: Elite
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: corsi-service
              uri: http://localhost:8080
              predicates:
                - Path= /corsi/**

            - id: docenti-discenti-service
              uri: http://localhost:8081
              predicates:
                - Path= /docenti/**, /discenti/**
  jwt:
    secret: mySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLong
